version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - ./logs:/logs
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/users
    depends_on:
      postgres:
        condition: service_healthy


  frontend:
    build:
      context: ./frontend/my-app/
      dockerfile: dockerfile
    volumes:
      - ./frontend/my-app:/app 
      - /app/node_modules 
    ports:
      - "3000:3000"
    depends_on:
      - backend
      

  

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  celery-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: celery-worker
    restart: always
    command: ["celery", "-A", "auth", "worker", "--loglevel=info"]
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

  celery-beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: celery-beat
    restart: always
    command: ["celery", "-A", "auth", "beat", "--loglevel=info"]
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    build:
      context: ./nginx
      dockerfile: dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:





