# Use the Python image
FROM python:3.11

RUN apt-get update && apt-get install -y postgresql-client

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN  pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire backend directory
COPY . .

# Run database migrations and start the server
CMD ["sh", "./script.sh"]